config/routes.rb
  Rails.application.routes.draw do
    mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
  resources :contacts


  resources :contacts
  devise_for :users
  root to: "home#index"
  resources :users
  resources :blogs do
    resource :favarites, only: [:create,:destroy]
    resources :comments, only: [:create,:destroy]
    collection do
      get 'search'
      end
    end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favarites, dependent: :destroy

  attachment :image

  with_options presence: true do
    validates :title
    validates :body
  end

    def self.search(search)
      if search != ""
        Blog.where('title LIKE(?)', "%#{search}%")
      else
        Blog.all
      end
    end
end  

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  belongs_to :user  
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favarite.rb
class Favarite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
  validates_uniqueness_of :blog_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favarites, dependent: :destroy


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         attachment :profile_image

    validates :username, presence: true    

    def already_favarited?(blog)
      self.favarites.exists?(blog_id: blog.id)
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == 'admin' && password == '2222'
    end
  end
  
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @blogs = Blog.order(id: "DESC")
  end

  def show
    @blog = Blog.find(params[:id])
    @comment = Comment.new
    @comments = @blog.comments.includes(:user)
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    if @blog.save
      redirect_to blog_path(@blog),notice: '投稿に成功しました'
    else
      render :new
    end
  end

  def edit
    @blog = Blog.find(params[:id])
    if @blog.user !=  current_user
      redirect_to blogs_path,alert: "不正なアクセスです"
    end
  end


  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
    redirect_to blog_path(@blog),notice: "投稿に成功しました"
    else
    render :edit
    end
   end

  def destroy
    blog = Blog.find(params[:id])
    blog.destroy
    redirect_to user_path(blog.user), notice: "レシピを削除しました。"
  end

  def search
    @blogs = Blog.search(params[:keyword])
  end

  private

  def blog_params
    params.require(:blog).permit(:title,:body,:image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.create(comment_params)
    redirect_to "/blogs/#{comment.blog.id}"
  end

  def destroy
    @comment = Comment.find(params[:id])
    @blog = @comment.blog
    @comment.destroy
    redirect_to blog_path(@blog)
  end


  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, blog_id: params[:blog_id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  def index
    @contacts = Contact.all
  end

  def show
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to contacts_path,notice: 'Contact was successfully created.'
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favarites_controller.rb
class FavaritesController < ApplicationController

  def create
    
    @favatrite = current_user.favarites.create(blog_id: params[:blog_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    
    @blog = Blog.find(params[:blog_id])
    @favatrite = current_user.favarites.find_by(blog_id: @blog.id)
    @favatrite.destroy
    redirect_back(fallback_location: root_path)
  end  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user !=  current_user
      redirect_to blogs_path,alert: '不正なアクセスです'
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favarites_helper.rb
module FavaritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_blog.html.erb
  <div class="content_post" style="background-image: url(<%= blog.image %>);">
      <div class="more">
        <span><%= image_tag "#" %></span>
        <ul class="more_list">
          <li>
            <%= link_to '詳細', blog_path(blog.id), method: :get %>
          </li>
            <% if user_signed_in? && current_user.id == blog.user_id %>
          <li>
            <%= link_to '編集', edit_blog_path(blog.id), method: :get %>
          </li>
          <li>
              <%= link_to '削除', blog_path(blog.id), method: :delete %>
          </li>
          <% end %>
        </ul>
      </div>
      <p><%= blog.title %></p>
          <span class="name">
      <a href="/users/<%= blog.user.id %>">
        <span>投稿者</span><%= blog.user.username %>
      </a>
    </span>
    
  </div>

app/views/blogs/edit.html.erb
<%= form_with model: @blog, local: true do |f| %>
 <div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %>
    </div>
 <div class="field">
  <%= f.label :body %>
  <%= f.text_area :body %>
    </div>
 <div class="field">
  <%= f.label :image %>
  <%= f.attachment_field :image %>
  </div>
 <div class="action">
  <%= f.submit %>
  </div>

<% end %>

app/views/blogs/index.html.erb
<div class="row">
  <% @blogs.each do |blog|%> 
    <div class="col-4">
      <div class="card" >
        <%= link_to blog_path(blog) do %>
          <%= attachment_image_tag blog, :image, class: "card-img-top" %><br>
        <% end %>
        <div class="card-body">
          <h5 class="card-title">
          <%= link_to blog.user.username,user_path(blog.user.id) %><br>
          <%= blog.updated_at.strftime("%Y-%m-%d %H:%M") %>更新</h5>
        </div>
        <% if current_user.already_favarited?(blog) %>
          <%= link_to  blog_favarites_path(blog), method: :delete do %>
          <i class="fas fa-heart"></i>
          <% end %>
        <% else %>
          <%= link_to  blog_favarites_path(blog), method: :post do %>
          <i class="far fa-heart"></i>
          <% end %>
          <%= blog.favarites.count %>
      <% end %> 
      </div>
    </div>
  <% end %>
</div>

app/views/blogs/new.html.erb
<%= form_with model: @blog, local: true do |f| %>
<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>
<div class="field">
  <%= f.label :body %>
  <%= f.text_area :body %>
</div>
<div class="field">
  <%= f.label :image %>
  <%= f.attachment_field :image %>
</div>
<div class="action">
  <%= f.submit %>
</div>
  <% end %>

app/views/blogs/search.html.erb
<%= form_with(url: search_blogs_path, local: true, method: :get, class: "search-form") do |form| %>
  <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "search-input" %>
  <%= form.submit "検索", class: "search-btn" %>
  <% end %>
<div class="contents row">
  <% @blogs.each do |blog| %>
    <%= render partial: "blog", locals: { blog: blog } %>
  <% end %>
</div>

app/views/blogs/show.html.erb
<div class="row">
  <div class="col-6">
      <div class="card" >
        <%= attachment_image_tag @blog, :image %>
        <div class="card-body">
          <h5 class="card-title">
          <%= @blog.title %>
          <%= simple_format @blog.body %>
        </div>
        <% if @blog.user.id == current_user.id %>
          <%= link_to "編集", edit_blog_path(@blog),class: "button is-succes" %>
        <% end %>
        <%= link_to @blog.user.username , user_path(@blog.user)  %><br>
        <%= @blog.user.profile %>




  <% if current_user.already_favarited?(@blog) %>
    <%= link_to  blog_favarites_path(@blog), method: :delete do %>
      <i class="fas fa-heart"></i>
    <% end %>
      <% else %>
    <%= link_to  blog_favarites_path(@blog), method: :post do %>
      <i class="far fa-heart"></i>
    <% end %>
    <%= @blog.favarites.count %>
  <% end %>

  <div class="container">
    <% if user_signed_in? %>
      <%= form_with(model: [@blog, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
      <% else %>
      <strong><p>※※※ コメントの投稿には新規登録/ログインが必要です ※※※</p></strong>
    <% end %>
    <div class="comments">
      <p>コメント一覧</p>
      <% @comments.each do |comment| %>
        <p>
          <strong><%= link_to comment.user.username, "/users/#{comment.user_id}" %>：</strong>
          <%= comment.text %>
        </p>
        <%= link_to "削除", blog_comment_path(@blog,comment), method: :delete ,class: 'btn btn-default'%>
      <% end %>
  </div>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>お問い合わせ</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/index.html.erb
     <div class="columns is-centered">
    <div class="column">
      <figure>
        <div class="main-image"></div>
        <p>あなたのおすすめの本を紹介するアプリ</p>
      </figure>
    </div>
  </div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ourblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>


    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" rel="stylesheet"> 

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="wrapper">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %> 
      <h1  style="font-family: cursive;">ourblog</h1>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
    <% if user_signed_in? %>
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item active">
          <%= link_to "投稿者一覧", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "マイページ", user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "投稿一覧", blogs_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規投稿", new_blog_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "お問い合わせ", new_contact_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      </ul>

      <%= form_with(url: search_blogs_path, local: true, method: :get, class: "d-flex") do |form| %>
        <%= form.text_field :keyword, placeholder: "投稿を検索する", class: "form-control me-2" %>
        <%= form.submit "検索", class: "btn btn-outline-success" %>
      <% end %>
    <% else %>
      <ul class="navbar-nav me-auto mb-2 mb-md-0">
        <li class="nav-item active">
          <%= link_to "ブログ投稿一覧", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
        </li>
      </ul>
    <% end %>
    </div>
  </div>
</nav>

   <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
<div class="wrapper">
<main class="container">
  <%= yield %>
</main>
  <footer>
      <p>
        Copyright ourbooks 2021.
      </p>
    </footer>
</div>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_with model: @user, local: true do |f| %>
<div class="field">
  <%= f.label :username %>
  <%= f.text_field :username %>
  </div>
  <div class="field">
  <%= f.label :email %>
  <%= f.text_field :email %>
  </div>
  <div class="field">
  <%= f.label :profile %>
  <%= f.text_area :profile %>
  </div>
  <div class="field">
  <%= f.label :profile_image %>
  <%= f.attachment_field :profile_image %>
  </div>
  <div class="action">
  <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<div class="row">
  <% @users.each do |user|%>
    <div class="col-4">
      <div class="card" >
        <%= link_to blog_path(user) do %>
          <%= attachment_image_tag user, :profile_image, fallback: "no-image.png",class: "card-img-top" %>
          <% end %>
        <div class="card-body">
          <h5 class="card-title">
          <%=link_to user.username, user_path(user) %><br>
          投稿数：<%= user.blogs.count %>
        </div>
      </div>
  </div>
   <% end %>
</div>

       

app/views/users/show.html.erb
<div class="row">
  <div class="col-6">
    <div class="card" >
        <%= attachment_image_tag @user, :profile_image, fallback: "no-image.png" , class: "profile_image "%><br>
        <%= @user.username %>
        <div class="card-body">
          <% if @user.id == current_user.id %> 
          <h5 class="card-title">
          <div class="field">
          <%= @user.email %>
          </div>
          <div class="field">
          <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
          <% end %>
          </div>
          <div class="field">
          <%= @user.profile %>
          </div>
    </div>
  </div>
</div>

<div class="row">
  <% @user.blogs.each do |blog|%>
    <div class="col-4">
      <div class="card" >
        <div class="field">
          <%= link_to blog_path(blog) do %>
            <%= attachment_image_tag blog, :image, fallback: "no-image.png",class: "mini-image" ,class: "card-img-top" %>
            <% end %>
            </div>
            <div class="field">
            <%= link_to blog_path(blog), class: "panel-block" do %>このブログを見る
            <% end %>
            </div>
          <% if @user.id == current_user.id %>
          <div class="field">
              <%= link_to edit_blog_path(blog), class: "panel-block" do %>このブログを編集する
              <% end %>
              </div>
              <div class="field">
            <%= link_to blog_path(blog), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>このブログを削除する
              <% end %>
              </div>
              <%= blog.updated_at.strftime("%Y-%m-%d %H:%M") %>更新
          <% end %>
        </div>
      </div>
    <% end %>
  </div>